### ISSUE TITLE
Initial Build of Pacakges for Monorepo Seems to Burn Down MacBook Air M1 Base Model

### ISSUE THREAD

**Issue by davidkutas** [visa/visa-chart-components#64]
When I attempt to build the packages initially for the monorepo with the `yarn dev --b` command, the computer becomes unresponsive. I'm wondering if this is specific to me, or if it does happen to others as well?! I know the note says that the initial build might take some time...

**Comment by chris-demartini** [comment]
Thanks for the comment on the @davidkutas. Can you try reducing the concurrency of the build process and let me know if that helps. In package.json change the build script to concurrency 2 or 4 instead of 8, which is what it is set to. 

I have not tried to build on an M1, but it does build on my old MacBook, if it struggles I reduce the concurrency to help the machine out a bit. 

Let us know if that helps.

**Comment by davidkutas** [comment]
I changed the concurrency to 2, and the issue got resolved. Thank you.

**Comment by chris-demartini** [comment]
Sounds good, we will try to add something to our docs to note this work around in an upcoming release.

**Comment by chris-demartini** [comment]
Addressed in latest release (6.3.0)
